### ISSUE TITLE
compatibility issue with sigma-cli 1.0.0

### ISSUE THREAD

**Issue by chenrui333** [SigmaHQ/pySigma-backend-sqlite#4]
While trying to upgrade homebrew package sigma-cli to 1.0.0 release, ran into some compatibility issue as show below:

```
$ pipgrip --tree sigma-cli
sigma-cli (1.0.0)
...
└── pysigma<0.12.0,>=0.11.3 (0.11.3)
...
```

```
$ pipgrip --tree pysigma-backend-sqlite
pysigma-backend-sqlite (0.1.1)
└── pysigma<0.11.0,>=0.10.5 (0.10.10)
...
```

**Comment by wagga40** [comment]
It should be OK on the plugin side with the release and the push to pypi.

But it does not solve your issue on the sigma-cli side (https://github.com/SigmaHQ/pySigma-plugin-directory/blob/main/pySigma-plugins-v1.json).

**Comment by wagga40** [comment]
Done on the sigma-cli side
